# Generated by Django 6.0.6 on 2026-06-21 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('idbingo', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebingo', models.CharField(max_length=100, verbose_name='Nombre del Evento Bingo')),
                ('fechabingo', models.DateField(verbose_name='Fecha del Bingo')),
            ],
            options={
                'verbose_name': 'Bingo',
                'verbose_name_plural': 'Bingos',
                'db_table': 'Bingo',
            },
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('idcarton', models.AutoField(primary_key=True, serialize=False)),
                ('numerocarton', models.IntegerField(unique=True, verbose_name='Número de Cartón Único')),
            ],
            options={
                'verbose_name': 'Cartón',
                'verbose_name_plural': 'Cartones',
                'db_table': 'Carton',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('idcuentabancaria', models.AutoField(primary_key=True, serialize=False)),
                ('nombrebanco', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('numerocuenta', models.CharField(max_length=50, unique=True, verbose_name='Número de Cuenta')),
                ('tipocuenta', models.CharField(max_length=50, verbose_name='Tipo de Cuenta (Ahorros/Corriente)')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'db_table': 'CuentaBancaria',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('idmetodopago', models.AutoField(primary_key=True, serialize=False)),
                ('nombremetodopago', models.CharField(max_length=50, unique=True, verbose_name='Método de Pago')),
                ('detallesmetodopago', models.CharField(blank=True, max_length=200, null=True, verbose_name='Detalles Opcionales')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'MetodoPago',
            },
        ),
        migrations.CreateModel(
            name='PlataformaJuego',
            fields=[
                ('idplataformajuego', models.AutoField(primary_key=True, serialize=False)),
                ('nombreplataforma', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Plataforma')),
            ],
            options={
                'verbose_name': 'Plataforma de Juego',
                'verbose_name_plural': 'Plataformas de Juego',
                'db_table': 'PlataformaJuego',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idprestamo', models.AutoField(primary_key=True, serialize=False)),
                ('montoprestamo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Solicitado')),
                ('tasainteres', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interés (%)')),
                ('plazomeses', models.IntegerField(verbose_name='Plazo en Meses')),
                ('fechasolicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fechaaprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('estadoprestamo', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Pagado', 'Pagado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20, verbose_name='Estado del Préstamo')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'db_table': 'Prestamo',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('idsocio', models.AutoField(primary_key=True, serialize=False)),
                ('cedulasocio', models.CharField(max_length=10, unique=True, verbose_name='Cédula de Identidad')),
                ('nombresocio', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidosocio', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fechanacimientosocio', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefonosocio', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('correosocio', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('direccionsocio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('fechaingresosocio', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('estadosocio', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'Socio',
            },
        ),
        migrations.CreateModel(
            name='TipoSocio',
            fields=[
                ('idtiposocio', models.AutoField(primary_key=True, serialize=False)),
                ('nombretiposocio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Socio')),
                ('roltiposocio', models.CharField(max_length=50, unique=True, verbose_name='Rol del Socio')),
                ('descripciondetiposocio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Socio',
                'verbose_name_plural': 'Tipos de Socio',
                'db_table': 'TipoSocio',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('idjugador', models.AutoField(primary_key=True, serialize=False)),
                ('nombrejugador', models.CharField(max_length=100, verbose_name='Nombre del Jugador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario del Sistema')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Jugador',
            },
        ),
        migrations.CreateModel(
            name='PartidaBingo',
            fields=[
                ('idpartidabingo', models.AutoField(primary_key=True, serialize=False)),
                ('horainicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('premio', models.CharField(max_length=200, verbose_name='Premio de la Partida')),
                ('idbingo', models.ForeignKey(db_column='idbingo', on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo', verbose_name='Bingo')),
            ],
            options={
                'verbose_name': 'Partida de Bingo',
                'verbose_name_plural': 'Partidas de Bingo',
                'db_table': 'PartidaBingo',
            },
        ),
        migrations.CreateModel(
            name='CartonPartidaBingo',
            fields=[
                ('idcartonpartidabingo', models.AutoField(primary_key=True, serialize=False)),
                ('estadocarton', models.CharField(default='Disponible', max_length=50, verbose_name='Estado del Cartón')),
                ('idpartidabingo', models.ForeignKey(db_column='idpartidabingo', on_delete=django.db.models.deletion.CASCADE, to='bingo.partidabingo', verbose_name='Partida de Bingo')),
            ],
            options={
                'verbose_name': 'Cartón en Partida',
                'verbose_name_plural': 'Cartones en Partidas',
                'db_table': 'CartonPartidaBingo',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.AutoField(primary_key=True, serialize=False)),
                ('montopago', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('fechapago', models.DateField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('idprestamo', models.ForeignKey(db_column='idprestamo', on_delete=django.db.models.deletion.CASCADE, to='bingo.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
                ('idsesionjuego', models.AutoField(primary_key=True, serialize=False)),
                ('fechasesion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Sesión')),
                ('idjugador', models.ForeignKey(db_column='idjugador', on_delete=django.db.models.deletion.CASCADE, to='bingo.jugador', verbose_name='Jugador')),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juego',
                'db_table': 'SesionJuego',
            },
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('idregalo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreregalo', models.CharField(max_length=100, verbose_name='Nombre del Regalo / Incentivo')),
                ('descripcionregalo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('fecharegalo', models.DateField(auto_now_add=True, verbose_name='Fecha de Entrega')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, to='bingo.socio', verbose_name='Socio Beneficiario')),
            ],
            options={
                'verbose_name': 'Regalo',
                'verbose_name_plural': 'Regalos',
                'db_table': 'Regalo',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='idsocio',
            field=models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, to='bingo.socio', verbose_name='Socio'),
        ),
        migrations.CreateModel(
            name='AporteSemanal',
            fields=[
                ('idaportesemanal', models.AutoField(primary_key=True, serialize=False)),
                ('montoaporte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Aporte')),
                ('fechapagoaporte', models.DateField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, to='bingo.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Aporte Semanal',
                'verbose_name_plural': 'Aportes Semanales',
                'db_table': 'AporteSemanal',
            },
        ),
        migrations.CreateModel(
            name='Ahorro',
            fields=[
                ('idahorro', models.AutoField(primary_key=True, serialize=False)),
                ('montoahorro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Ahorrado')),
                ('fechaahorro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('idsocio', models.ForeignKey(db_column='idsocio', on_delete=django.db.models.deletion.CASCADE, to='bingo.socio', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Ahorro',
                'verbose_name_plural': 'Ahorros',
                'db_table': 'Ahorro',
            },
        ),
        migrations.AddField(
            model_name='socio',
            name='idtiposocio',
            field=models.ForeignKey(db_column='idtiposocio', on_delete=django.db.models.deletion.CASCADE, to='bingo.tiposocio', verbose_name='Tipo de Socio'),
        ),
    ]
